import { describe, expect, it } from "vitest";
import { negotiate, totalCostOfOwnership, accuracyCostCurve, conceptDrift, cosineSimilarity, shadowCompare, explorationChoice, validateDelegationContract, composeSquad, optimizeContext, strictRequiredFields, jitteredBackoff, timeoutDecision, FailureMemoryStore, asyncBatches, globalReward, preferencePenalty, heuristicFastPath, uncertaintyFallback, ServiceRegistry, handleWebhook, postmortem, privacyArchitecture, conflictDecision, techRadar } from "../src/meta-architecture-skills.js";

describe("Meta-Architecture operating skills", () => {
  it("negotiates with BATNA and quantifies TCO", () => { expect(negotiate([{ id: "a", value: 10, cost: 2, risk: 1 }, { id: "b", value: 8, cost: 1, risk: 1 }], "b").preferred).toBe("a"); expect(totalCostOfOwnership({ infrastructure: 1, api: 2, security: 3, tuning: 4, team: 5 })).toBe(15); expect(accuracyCostCurve([{ accuracy: .98, cost: 3 }, { accuracy: .95, cost: 1 }])[0]?.accuracy).toBe(.95); });
  it("detects drift and compares shadow candidates", () => { expect(cosineSimilarity([1, 0], [1, 0])).toBe(1); expect(conceptDrift(.9, .8).drift).toBe(true); expect(shadowCompare(.8, .9).winner).toBe("candidate"); expect(explorationChoice("stable", "exp", .01).exploratory).toBe(true); });
  it("enforces delegation, squads, context and strict validation", () => { expect(validateDelegationContract({ inputSchema: "in", outputSchema: "out", latencyMs: 200, auditRequired: true })).toBe(true); expect(composeSquad([{ role: "ml", capability: "model" }, { role: "ml", capability: "model" }])).toHaveLength(1); expect(optimizeContext(["1", "2", "3", "4"], 10).recent).toEqual(["2", "3", "4"]); expect(strictRequiredFields({ a: 1 }, ["a", "b"]).missing).toEqual(["b"]); });
  it("handles resilience, failure memory, reward and human fallback", () => { expect(jitteredBackoff(3, 100, 1000)).toBe(720); expect(timeoutDecision(120, 100, "partial").complete).toBe(false); const store = new FailureMemoryStore<string>(); store.record({ fingerprint: "x", prompt: "p", error: "e", count: 1 }); expect(store.find("x")?.error).toBe("e"); expect(asyncBatches([1,2,3], 2)).toEqual([[1,2],[3]]); expect(globalReward({ reward: 1, hallucinationPenalty: .1, computeCost: .2, riskPenalty: .1 })).toBeCloseTo(.6); expect(preferencePenalty({ positive: 5, negative: 2 })).toBe(3); expect(heuristicFastPath(.95)).toBe("reject"); expect(uncertaintyFallback(.97)).toBe("human"); });
  it("provides service discovery, webhook replay protection and conflict handling", () => { const registry = new ServiceRegistry(); registry.register({ name: "a", version: "1", capabilities: ["search"] }); expect(registry.discover("search")).toHaveLength(1); const seen = new Set<string>(); const job = { id: "j", status: "complete" as const, result: 1 }; expect(handleWebhook(job, "e1", seen).accepted).toBe(true); expect(handleWebhook(job, "e1", seen).accepted).toBe(false); expect(postmortem("failure", "gap").blameFree).toBe(true); expect(privacyArchitecture(["public", "secret"], ["public"]).blocked).toEqual(["secret"]); expect(conflictDecision([1,2,3], (x) => x)).toBe(3); expect(techRadar([1,3,2], (x) => x)).toEqual([3,2,1]); });
});
